apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs3900-backend-deployment
  labels:
    app.kubernetes.io/name: cs3900-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cs3900-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cs3900-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/unsw-cse-comp99-3900-24t1/capstone-project-3900w11athecsgoons-backend:sha-56f19eb
        volumeMounts:
        - mountPath: "/usr/src/ssl"
          name: ssl-certs
          readOnly: true
        ports:
        - containerPort: 8443
          name: https
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "6Gi"
            cpu: "1"
        # TODO livenessProbe
      volumes:
      - name: ssl-certs
        secret:
          secretName: cs3900-ssl-certificate-secret
      imagePullSecrets:
      - name: ghcr-pull-credential-secret
