apiVersion: v1
kind: Service
metadata:
  name: cs3900-backend-svc
  labels:
    app.kubernetes.io/name: cs3900-backend
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  selector:
    app.kubernetes.io/name: cs3900-backend
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8443
