apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs3900-backend-deployment
  labels:
    app.kubernetes.io/name: cs3900-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cs3900-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cs3900-backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.5
        volumeMounts:
        - mountPath: "/etc/nginx/ssl"
          name: nginx-ssl
          readOnly: true
        - mountPath: "/etc/nginx/conf.d"
          name: nginx-conf
          readOnly: true
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      volumes:
      - name: nginx-ssl
        secret:
          secretName: cs3900-ssl-certificate-secret
      - name: nginx-conf
        secret:
          secretName: cs3900-nginx-conf-secret
